SIG/SIG/urls.py
from django.contrib import admin
from django.urls import path
from webapp.views import bienvenido
from shapefile.views import verMapa, cargarArchivoVista, cargarArchivo #importación de los metodos

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', bienvenido, name='inicio'),
    
    path('ver_mapa/', verMapa, name='mapa'),
    #path('ver_shapefile/', verShapefile), #Creación del path para ver un registro
    #path('agregar_departamento/',nuevoDepartamento, name='departamento'), #Creacion del path para agregar un registro de departamento
    #path('agregar_municipio/',nuevoMunicipio), #Creacion del path para agregar un registro de municipio
    #path('agregar_puntoMina/',nuevoMinasPoint), #Creacion del path para agregar un registro de punto de mina
    path('cargar_archivo/', cargarArchivoVista),
    path('cargar_archivo/post/', cargarArchivo, name='cargar_archivo'),
]

SIG/shapefile/models.py
from django.contrib.gis.db import models


# Create your models here.

class MinasPoint(models.Model):
        gid = models.AutoField(primary_key=True)
        departamen = models.CharField(80)
        cod_dep = models.CharField(80)
        municipio = models.CharField(80)
        cod_mun = models.CharField(80)
        zona = models.CharField(80)
        vereda = models.CharField(80)
        ano = models.CharField(80)
        mes = models.CharField(80)
        edad = models.CharField(80)
        ocupacion = models.CharField(80)
        genero = models.CharField(80)
        condicion = models.CharField(80)
        y = models.DecimalField(max_digits=10, decimal_places=10)
        x = models.DecimalField(max_digits=10, decimal_places=10)
        lugar_deto = models.CharField(80)
        actividad = models.CharField(80)
        y_cmt12 = models.CharField(80)
        x_cmt12 = models.CharField(80)
        geom = models.GeometryField(srid=4326)
        

        def __str__(self):
            return str(self.gid)

SIG/shapefile/forms.py
from django.forms import ModelForm, EmailInput, TextInput, NumberInput
from shapefile.models import MinasPoint
from django import forms
from django.contrib.gis.geos import Point




class MinasPointForm(forms.ModelForm):
    class Meta:
        model = MinasPoint
        fields = ['departamen', 'cod_dep', 'municipio', 'cod_mun', 'zona', 
                  'vereda', 'ano', 'mes', 'edad', 'ocupacion', 'genero', 
                  'condicion', 'y', 'x', 'lugar_deto', 'actividad', 
                  'y_cmt12', 'x_cmt12']  # Sin geom
        widgets = {
            'ano': forms.TextInput(attrs={'type': 'text'}),
            'mes': forms.TextInput(attrs={'type': 'text'}),
            'edad': forms.TextInput(attrs={'type': 'text'}),
            'ocupacion': forms.TextInput(attrs={'type': 'text'}),
            'genero': forms.TextInput(attrs={'type': 'text'}),
            'condicion': forms.TextInput(attrs={'type': 'text'}),
            'y': forms.NumberInput(attrs={'type': 'number'}),
            'x': forms.NumberInput(attrs={'type': 'number'}),
            'actividad': forms.TextInput(attrs={'type': 'text'}),
            'y_cmt12': forms.TextInput(attrs={'type': 'text'}),
            'x_cmt12': forms.TextInput(attrs={'type': 'text'}),
            
        }

SIG/shapefile/views.py
from django.shortcuts import render, get_object_or_404, redirect
from shapefile.forms import MinasPointForm
from django.contrib.gis.geos import Point
from shapefile.models import MinasPoint
from django.http import JsonResponse
from django.core.serializers import serialize
from rest_framework.response import Response
from rest_framework import status
import shapefile
from rest_framework.decorators import api_view
from django.core.files.storage import default_storage
import os
import geopandas as gpd
import pandas as pd
import tempfile
from decimal import Decimal


# Create your views here.



def verMapa(request):
    # Obtener los puntos y serializarlos a GeoJSON
    puntos = MinasPoint.objects.all()
    geojson_data = serialize('geojson', puntos, geometry_field='geom', fields=('ocupacion', 'genero', 'lugar_deto'))

    # Verifica si la solicitud es AJAX
    if request.headers.get('x-requested-with') == 'XMLHttpRequest':
        return JsonResponse(geojson_data, safe=False)

    # Si no es AJAX, renderiza la plantilla HTML
    return render(request, 'gis/mapa.html', {'geojson_data': geojson_data})

#def nuevoDepartamento(request):
#    if request.method == 'POST':
 #       formaDepartamento = DepartamentoForm(request.POST)
  #      if formaDepartamento.is_valid():
   #         formaDepartamento.save()
 #           return redirect('inicio')
  #  else:
   #     formaDepartamento = DepartamentoForm()

    #return render(request, 'departamentos/agregar_departamento.html' , {'formaDepartamento': formaDepartamento})

#def nuevoMunicipio(request):
 #   if request.method == 'POST':
  #      formaMunicipio = MunicipioForm(request.POST)
   #     if formaMunicipio.is_valid():
    #        formaMunicipio.save()
     #       return redirect('inicio')
  #  else:
   #     formaMunicipio = MunicipioForm()
#
 #   return render(request, 'municipios/agregar_municipio.html' , {'formaMunicipio': formaMunicipio})



#def nuevoMinasPoint(request):
 #   if request.method == 'POST':
  #      formaMinasPoint = MinasPointForm(request.POST)
   #     if formaMinasPoint.is_valid():
    #        # Obtener las coordenadas de X y Y
     #       x = formaMinasPoint.cleaned_data['x']
      #      y = formaMinasPoint.cleaned_data['y']
       #     point = Point(x, y, srid=4326)  # Crea un objeto Point con las coordenadas
#
 #           # Guardar la instancia de MinasPoint
  #          mina = formaMinasPoint.save(commit=False)
   #         mina.geom = point  # Asigna el objeto Point al campo geom
    #        mina.save()
#
 #           return redirect('inicio')  # Redirige a la vista de inicio
  #  else:
   #     formaMinasPoint = MinasPointForm()
#
 #   return render(request, 'minas/agregar_puntoMina.html', {'formaMinasPoint': formaMinasPoint})



def cargarArchivoVista(request):
    return render(request, 'archivo/cargar_archivo.html')  # Invoca la plantilla con el formulario


@api_view(['POST'])
def cargarArchivo(request):
    shapefile_shp = request.FILES.get('shapefile_shp')
    shapefile_shx = request.FILES.get('shapefile_shx')
    shapefile_dbf = request.FILES.get('shapefile_dbf')
    shapefile_cpg = request.FILES.get('shapefile_cpg')
    shapefile_pjr = request.FILES.get('shapefile_pjr')
    shapefile_qmd = request.FILES.get('shapefile_qmd')

    if not (shapefile_shp or shapefile_shx or shapefile_dbf or shapefile_cpg or shapefile_pjr or shapefile_qmd):
        return Response({'error': 'No se ha proporcionado ningún archivo .shp o .shx o .dbf o . cpg o .pjr o .qmd'}, status=status.HTTP_400_BAD_REQUEST)

    try:
        with tempfile.TemporaryDirectory() as temp_dir:
            shp_path = os.path.join(temp_dir, 'temp_shapefile.shp')
            with open(shp_path, 'wb') as f:
                for chunk in shapefile_shp.chunks():
                    f.write(chunk)

            if not os.path.exists(shp_path):
                return Response({'error': 'El archivo .shp no se guardó correctamente'}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

            shx_path = os.path.join(temp_dir, 'temp_shapefile.shx')
            with open(shx_path, 'wb') as f:
                for chunk in shapefile_shx.chunks():
                    f.write(chunk)
            
            dbf_path = os.path.join(temp_dir, 'temp_shapefile.dbf')
            with open(dbf_path, 'wb') as f:
                for chunk in shapefile_dbf.chunks():
                    f.write(chunk)

            cpg_path = os.path.join(temp_dir, 'temp_shapefile.cpg')
            with open(cpg_path, 'wb') as f:
                for chunk in shapefile_cpg.chunks():
                    f.write(chunk)

            pjr_path = os.path.join(temp_dir, 'temp_shapefile.pjr')
            with open(pjr_path, 'wb') as f:
                for chunk in shapefile_pjr.chunks():
                    f.write(chunk)

            # Leer el shapefile usando GeoPandas
            gdf = gpd.read_file(shp_path)

            print("Columnas del DataFrame:", gdf.columns)

            # Después de leer el shapefile
            gdf = gpd.read_file(shp_path)
            print(gdf.head())  # Imprime las primeras filas del DataFrame
            print(gdf.columns)  # Imprime los nombres de las columnas

            
            # Procesar cada fila en el DataFrame
            for _, row in gdf.iterrows():
    #            y = row['Y']  # Usar el valor directamente de la fila
    #            x = row['X']  # Usar el valor directamente de la fila
                y_str = str(row['Y']).replace(',', '').replace('.','').strip()  # Eliminar comas, puntos y espacios
                x_str = str(row['X']).replace(',', '').replace('.','').strip()  # Eliminar comas, puntos y espacios

                try:
                    y = float(y_str)  # Convertir a float sin redondear
                    x = float(x_str)  # Convertir a float sin redondear
                except ValueError:
                    return Response({'error': f'El valor {y_str} o {x_str} no es un número válido'}, status=status.HTTP_400_BAD_REQUEST)


                # Verificar que X e Y no sean nulos
                if pd.isnull(y) or pd.isnull(x):
                    return Response({'error': 'El shapefile contiene puntos sin coordenadas válidas'}, status=status.HTTP_400_BAD_REQUEST)

                # Si X e Y son válidos, procedemos a crear el objeto
                MinasPoint.objects.create(
                    departamen = row['Departamen'],
                    cod_dep=row['Cod_dep'],
                    municipio = row['Municipio'],
                    cod_mun=row['Cod_mun'],
                    zona = row['Zona'],
                    vereda = row['Vereda'],
                    ano=row['Ano'],
                    mes=row['Mes'],
                    edad=row['Edad'],
                    ocupacion=row['Ocupacion'],
                    genero=row['Genero'],
                    condicion=row['Condicion'],
                    y=y,  # Usar el valor directamente de la fila
                    x=x,  # Usar el valor directamente de la fila
                    lugar_deto=row['Lugar_deto'],
                    actividad=row['Actividad'],
                    y_cmt12=row['Y_CMT12'],
                    x_cmt12=row['X_CMT12'],
                    geom= Point(x, y, srid=4326)  
                )

    except Exception as e:
        return Response({'error': str(e)}, status=status.HTTP_500_INTERNAL_SERVER_ERROR)

    return Response({'status': 'Archivos cargados correctamente'}, status=status.HTTP_201_CREATED)

SIG/shapefile/templates/minas/agregar_puntoMina.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>Nuevo punto de mina</title>
    </head>
    <body>
        <form method="POST">
            <h1>Agregar punto de mina</h1>
            <table>
                <tr>
                    <td><label for="id_cod_departamento">Departamento:</label></td>
                    <td>{{ formaMinasPoint.cod_departamento }}</td>
                </tr>
                <tr>
                    <td><label for="id_cod_municipio">Municipio:</label></td>
                    <td>{{ formaMinasPoint.cod_municipio }}</td>
                </tr>
                <tr>
                    <td><label for="id_anyo">Año:</label></td>
                    <td>{{ formaMinasPoint.anyo }}</td>
                </tr>
                <tr>
                    <td><label for="id_mes">Mes:</label></td>
                    <td>{{ formaMinasPoint.mes }}</td>
                </tr>
                <tr>
                    <td><label for="id_edad">Edad:</label></td>
                    <td>{{ formaMinasPoint.edad }}</td>
                </tr>
                <tr>
                    <td><label for="id_ocupacion">Ocupación:</label></td>
                    <td>{{ formaMinasPoint.ocupacion }}</td>
                </tr>
                <tr>
                    <td><label for="id_genero">Género:</label></td>
                    <td>{{ formaMinasPoint.genero }}</td>
                </tr>
                <tr>
                    <td><label for="id_condicion">Condición:</label></td>
                    <td>{{ formaMinasPoint.condicion }}</td>
                </tr>
                <tr>
                    <td><label for="id_y">Y:</label></td>
                    <td>{{ formaMinasPoint.y }}</td>
                </tr>
                <tr>
                    <td><label for="id_x">X:</label></td>
                    <td>{{ formaMinasPoint.x }}</td>
                </tr>
                <tr>
                    <td><label for="id_lugar_deto">Lugar de Detención:</label></td>
                    <td>{{ formaMinasPoint.lugar_deto }}</td>
                </tr>
                <tr>
                    <td><label for="id_actividad">Actividad:</label></td>
                    <td>{{ formaMinasPoint.actividad }}</td>
                </tr>
                <tr>
                    <td><label for="id_x_cmt12">X CMT12:</label></td>
                    <td>{{ formaMinasPoint.x_cmt12 }}</td>
                </tr>
                <tr>
                    <td><label for="id_y_cmt12">Y CMT12:</label></td>
                    <td>{{ formaMinasPoint.y_cmt12 }}</td>
                </tr>
                
            </table>
            <button type="submit">Guardar</button>
            {% csrf_token %}
        </form>
    </body>
</html>